spring:
  datasource:
    url: jdbc:mysql://csl-2019-db.cphkcpsmvvem.ap-northeast-2.rds.amazonaws.com:3306/csl_db?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: csl_user
    password: csl2016!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
